### ISSUE TITLE
How to receive buttons

### ISSUE THREAD

**Issue by vladismile** [telegram-bot-rb/telegram-bot#104]
Hi!
My bot was added to channel as admin. So i can receive any messages which are posted in it.
I know how to get text or attachments from messages, but can't get buttons...
Is it possible?

**Comment by printercu** [comment]
Hi!
I don't know. There is `#update` method which return received update without modifications. If it does not contain any data related to buttons, I think it's impossible to get this data.
Your question is not related to gem itself, StackOverflow may be the better option to ask it, because its community is not limited to this gem users.
