### ISSUE TITLE
How to handle Telegram::Bot::Error in Telegram::Bot::Client::AsyncJob

### ISSUE THREAD

**Issue by caecity43** [telegram-bot-rb/telegram-bot#107]
I got `Telegram::Bot::Error: Bad Request: Bad Request: chat not found` error in Sidekiq retries.

How to handle it? 

Thanks.

**Comment by printercu** [comment]
Hi!
If you use default job, then it's gonna be ActiveJob. Here are docs on error handling: https://api.rubyonrails.org/classes/ActiveJob/Exceptions.html (see ClassMethods too)
You can call this methods in initializer:
```ruby
Telegram::Bot::Client::AsyncJob.rescue_from(Telegram::Bot::Error) do |error|
  do_something_with(error)
end
```

Previously there was StaleChat error, but I had to remove it because Telegram changes error messages very frequently and have no docs on it: https://github.com/telegram-bot-rb/telegram-bot/commit/817af95369d5f8ce0829ae40e548ba950daec0f0#diff-a7c219a4b93800791a0d25296c66eb60. So now app is responsive for handling errors in right way.

**Comment by printercu** [comment]
Here is a trick to make handler work with hot-reloads:

```ruby
# initializer
Telegram::Bot::Client::AsyncJob.rescue_from(Telegram::Bot::Error) do |error|
  TelegramJobErrorHandler.handle(error)
end

# telegram_job_error_hadler.rb
# in any directory from autoload_path (like app/models)
module TelegramJobErrorHandler
  module_function

  def handle(error)
    # do the stuff
  end
end
```

**Comment by printercu** [comment]
Closing due to no response. Feel free to ping me to reopen it.

**Comment by caecity43** [comment]
I got `NameError: uninitialized constant Telegram::Bot::Client::AsyncJob` error.

```ruby
class ApplicationJob < ActiveJob::Base

  Telegram::Bot::Client::AsyncJob.rescue_from(Telegram::Bot::Error) do |error|
    Rails.logger.info error.inspect
  end

end
```

is that right for place to ApplicationJob?

**Comment by printercu** [comment]
Hi! Try `Telegram::Bot::Client.default_async_job` instead of `Telegram::Bot::Client::AsyncJob`.
