### ISSUE TITLE
How to set up webhook in a non-rails application

### ISSUE THREAD

**Issue by lioialessandro** [telegram-bot-rb/telegram-bot#109]
I'm using [this guide](https://github.com/telegram-bot-rb/telegram-bot/wiki/Not-rails-application) to create my bot.
This is my code
```
require 'telegram/bot'
require './BotController.rb'

bot = Telegram::Bot::Client.new(ENV["TELEGRAM_BOT_TOKEN"])

if ENV["BOT_ENV"] == "development"
  require 'logger'
  logger = Logger.new(STDOUT)
  poller = Telegram::Bot::UpdatesPoller.new(bot, BotController, logger: logger)
  run poller.start
else
  run Telegram::Bot::Middleware.new(bot, BotController)
end
```
So I'm using the poller method in development and I want to use the webhook method in production (it will be deployed to Heroku).
I don't know how to set it up for production use. I should set up somewhere the URL but I don't know where and how.
Can someone help me?

**Comment by printercu** [comment]
Hi! To run it in webhook mode, you need to use webserver (like puma/thin/unicorn). All (almost?) ruby webservers support rack interface (it's a gem to deal with http requests).
`run` is actually a rack method so you don't need it before `poller.start`, as it expects rack app as argument. See http://rack.github.io/ on how to run rack apps. `Telegram::Bot::Middleware.new(...)` is a rack app, but as I've mentioned in the guide, it's better to mount it on some secret endpoint because telegram does not sign webhooks, and attacker can send malicious webhooks if knows bot's endpoint. I don't know if rack has a built-in router. You can just add custom middleware which checks path prefix.

**Comment by lioialessandro** [comment]
I've removed the run in the poller method.
I've seen the http://rack.github.io/, I'm using the `config.ru` method and I run `rackup config.ru` from the command-line but I don't know how to set up the secret endpoint. Can you help me?
(I'm a total beginner in Ruby)

**Comment by lioialessandro** [comment]
So, I've looked up a few examples and tried to deploy my bot to Heroku.
What I've done is basically add this line:
```
bot.set_webhook(url: "#{ENV["URL"]}/bot#{ENV["TELEGRAM_BOT_TOKEN"]}")
```
Is it correct?

**Comment by printercu** [comment]
Looks like rack supports `map` method out of the box. So this should work:

```ruby
# Define BOT_PATH earlier or use inline "/bot#{ENV....}" from your previous comment
map "/#{BOT_PATH}" do
  run Telegram::Bot::Middleware.new(bot, BotController)
end
```

And set webhook url in telegram `bot.set_webhook(url: "#{HOST}/#{BOT_PATH}")`.

**Comment by lioialessandro** [comment]
Thank you for your help.
I'll close the issue.
