### ISSUE TITLE
Example for custom Async Job?

### ISSUE THREAD

**Issue by marckohlbrugge** [telegram-bot-rb/telegram-bot#122]
Would you mind providing a code example for writing a custom class for async jobs?

Here's what I have so far, but it's leading to some exceptions. I'm probably missing something obvious, but a working code example would be nice.

```ruby
class Telegram::AsyncJob < ApplicationJob
  include Telegram::Bot::Async::Job

  queue_as :default

  rescue_from Telegram::Bot::Forbidden do |e|
    raise unless ignored_messages.include?(e.message)
  end

  private

  def ignored_messages
    [
      "Forbidden: user is deactivated",
      "Forbidden: bot can't initiate conversation with a user",
      "Forbidden: bot was blocked by the user"
    ]
  end
end
```

**Comment by printercu** [comment]
Hi!

With `include Telegram::Bot::Async::Job` you need explicitly set `self.client_class = Telegram::Bot::Client`. Or better copy `#perform` from it instead of including.

I think defining custom job classes is useful only when ActiveJob is not available. With ActiveJob it's better to tune default job classes in `config/initializers/telegram-bot.rb`:
```ruby
Telegram::Bot::Client.default_async_job.class_eval do
  queue_as :default
  rescue_from ...
end
```

**Comment by marckohlbrugge** [comment]
@printercu Thanks for that suggestion. I didn't even think of that. Makes more sense indeed. 👍
