### ISSUE TITLE
RSpec. How i can test save_context, sessions?

### ISSUE THREAD

**Issue by s-anches** [telegram-bot-rb/telegram-bot#134]
Hi. You can help me? )) Subject.

**Comment by printercu** [comment]
Hi! In integration tests `session` object is usually treated as implementation detail, and should not be checked directly. Instead, effects of one request are tested in the result of the other. You can see in [example app](https://github.com/telegram-bot-rb/telegram_bot_app/blob/master/spec/requests/telegram_webhooks_spec.rb#L16): message saved to session in one request and its content is retrieved and asserted in the other.

However it's easy to test implementation details in ruby :) `controller.send(:session)` returns session after request. Note that this session is "read-only", because it has been written to storage at the end of request and this is just a "snapshot" of it's state. The only way to modify state without making a request is to write directly to session storage. I think this methods should be used as a last resort.

The other option is to use rails controller tests which are kind of unit tests for controllers. There are also helpers for such tests in this gem (see readme and [test](https://github.com/telegram-bot-rb/telegram-bot/blob/master/spec/telegram/bot/updates_controller/testing_spec.rb)). Session is mocked there and you have read-write access to it. As they have side effects and run code in the way different from production, they also should be used with caution.

**Comment by s-anches** [comment]
Thanks
