### ISSUE TITLE
Question about action_for_message_context

### ISSUE THREAD

**Issue by KonstantinReido** [telegram-bot-rb/telegram-bot#148]
Hi

Currently, I work on a system which loads logic of bot from DB. My telegram webhooks controller doesn't contain context-related action, so the gem rises AbstractController::ActionNotFound. To solve this, I override `action_for_message_context`, but it looks like a dirty solution. What if this behaviour of gem will be configurable? What do you think? I can try to provide PR if you think that it looks logical.

**Comment by printercu** [comment]
Hi!

Do you mean you load context name from DB? It looks like this is your app-specific logic and it's completely fine to override `action_for_message_context`. Another option is to check that there is a valid action in controller before setting a context with `action_method?(new_context)`.

`AbstractController::ActionNotFound` is raised intentionally because only developers have control over context name being saved (users can not set any arbitrary value as this can appear for commands where user is able to send any command). So this exception means that context name was misspelled most likely or handler was not defined.

**Comment by KonstantinReido** [comment]
@printercu I trying to put all bot's logic into DB. Redefined `action_for_message_context`, but not sure why in your code you doing this
```
action = context.to_s
```
Currently, I did in this way
```
def action_for_message_context(context)
  context
end
```

**Comment by printercu** [comment]
Looks like `.to_s` is legacy, everything should work fine without it (tests are passed).

**Comment by printercu** [comment]
Anyway it's just a noop when `context` is a string so it's not a problem to have it.
