### ISSUE TITLE
how to use method

### ISSUE THREAD

**Issue by armanlearn** [telegram-bot-rb/telegram-bot#40]
Hi

how should i use these methods?
https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/client.rb

is this true ?
reply_with :sendDocument, pdf: File.open('~/work/a.pdf')

**Comment by printercu** [comment]
Hi!

`pry` gem with it's `show-method` may help you discover gem's source. You may use `show-method YourControllerName#reply_with` in pry console. This will bring you to https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/reply_helpers.rb#L10 And you can see that `reply_with/respond_with` are just shortcuts for `bot.send_#{type}`. So you need `reply_with :document, pdf: ...`. Also you can explicitly call `bot.send_document chat_id: ..., pdf: ....`.

All the api methods in `Client` are just a shortcuts provided in a ruby-friendly way with underscored names. Here is readme section on how to call any api method, even if gem does not provide a shortcut: https://github.com/telegram-bot-rb/telegram-bot#client

**Comment by armanlearn** [comment]
many tanks

**Comment by armanlearn** [comment]
sorry again 

I wrote this line of code

          reply_with :photo, photo: File.open('users/myuser/Downloads/a.jpg')

robot hang and not send anything. 

is this because I am in development env and I am in localhost ?

**Comment by armanlearn** [comment]
for pdf look at this code

                            reply_with :document, pdf: File.open('/users/mycomputer/Downloads/a.pdf')

and result in terminal is like this

Responded with document
Completed in 9731ms
Bad Request: Bad Request: there is no document in the request
/Users/mycomputer/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/telegram-bot-4f47506e22d4/lib/te

**Comment by armanlearn** [comment]
ok I make my jpg file size very small and get respond 
but for document I want to send 10 Mbytes pdf file

**Comment by printercu** [comment]
Please see the API docs: https://core.telegram.org/bots/api#senddocument
It requires `document` instead of `pdf` and have size limit at 50mb. I used `pdf` in example only because of your first message, where you already had `pdf` field.

Please use github issues for reporting about bugs/feature requests. I see your questions as not related to gem itself but about basic telegram api usage, learning programming.

My advice is to use more appropriate resources like google groups and stackoverflow for such discussions, and pay more attention when reading documentations.

Thank you for understanding.

**Comment by armanlearn** [comment]
solved tanks.

**Comment by armanlearn** [comment]
should use document: not pdf:
