### ISSUE TITLE
429 Error when >30 message

### ISSUE THREAD

**Issue by dsounded** [telegram-bot-rb/telegram-bot#77]
Hi guys, thanks for the gem!

I am trying to use it for my hobby project. The interesting thing, from telegram API I saw that I can't send more than 30 message per seconds after that I should receive 429 error, but looks like you already handle this somewhere(tried to find in sources, but had no luck). So it seems to use batches, f.e. if I want to  send 108 messages it sends 30+30+30+18 respectively. Is that by design ?

**Comment by printercu** [comment]
Hi!

> but looks like you already handle this somewhere

I don't remember implementing this. The idea was to keep client simple. There is async mode, where request is performed in a job, and job adapter will retry any error (including described one) automatically. But this won't be a good solution, because it will retry all the batch (78, then 48 again, then 18 again :) ).

The limit is applied by telegram: https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
I'm not sure if this limit is applied when you sending a lot of different messages just because you have a lot of users interacting with the bot at the moment (not broadcasting).

**Comment by printercu** [comment]
Yes. That is what i'm talking about: all request are processed separately. And if you use async mode, first 30 will be successful and 78 will fail. On the next retry 30 more will be successful and 48 retried. And so on.

The easiest approach is just to `chat_ids.each_slice(30 or less) { |batch| batch.each { |x| send_message }; sleep 1 } `

**Comment by dsounded** [comment]
The problem why I digging into all of this is hosting, since it my own pet project I tried to use Heroku standard pack, it works OK for small amount of users, but fails with 100+. I tried `async: true`, wdyt can it make the process faster ? It especially fails when multiple user clicks inline buttons(10 seconds timeout for the answer_callback_query)

**Comment by dsounded** [comment]
I tried that way with the sleep, but benchmarks for the result is pretty equal as just leave it without handling, for 108 messages it takes avg 14-22 seconds...

**Comment by dsounded** [comment]
And, how can I see the code, where retries happens ? I do believe in retries after some period, I'd like to minimize that period to 1 second if it's possible

**Comment by printercu** [comment]
> And, how can I see the code, where retries happens ? I do believe in retries after some period, I'd like to minimize that period to 1 second if it's possible

It depends on job adapter you use

**Comment by dsounded** [comment]
Sidekiq

**Comment by printercu** [comment]
Via active_job or plain? It can be tuned for both, please look for `retry timeout` in docs.

**Comment by printercu** [comment]
You can speedup the sample with `sleep` by wrapping `send_message` with `Thread { new }`. This will help, because it's mostly network request and will release GIL. Async mode can do almost the same, with little overhead.

**Comment by dsounded** [comment]
I tried Thread.new { send my batch here for 25 messages } in loop until I send all of them in separate threads, this at least allow me to unblock main thread faster

**Comment by printercu** [comment]
This is slightly different from what I proposed. I'm suggesting `batch.map { |x| Thread.new { send to x } }`. This will make all messages in batch being sent almost simultaneously.

Make sure you understand drawbacks of using threads: `sleep 1` here does not guarantee that you won't get 429 again, because some requests may take longer and other batch will start before previous one is finished, or some requests were sent from other thread (ex., in response to incoming messages). Making fast & reliable broadcaster is challenging task. Maybe there is a gem which implements such throttling.

_Small advise:_ It's good idea to rescue and report/log errors inside every created thread, because ruby (< 2.5) silently suppresses them by default.

**Comment by dsounded** [comment]
Maybe I sent wrong code example, but I did the same as you've described before )

**Comment by printercu** [comment]
Closing this issue?

**Comment by dsounded** [comment]
Yes, I think so, thanks for you time!
