### ISSUE TITLE
Is there a way to hide stuff after it's written and only show result to specific user?

### ISSUE THREAD

**Issue by bctoh** [telegram-bot-rb/telegram-bot#97]
1. Is there a way to hide /commands after it's called the function?
2. Is there a way to only show /help function to the specific user who called it?

Cheers.

**Comment by printercu** [comment]
1. May be this can work: https://core.telegram.org/bots/api#replykeyboardremove
2. I don't think it's possible. In a group chat every user gets all messages.

I think it's better to ask such questions on StackOverflow, because they are not related to the gem itself. There you can get answers from larger community, I think they can be more helpful.
